# dirs
display_name: test_domain_18_model
dataset_path_dir:  ../dataset_domain/domain18
models_save_dir: test_domain_18_model
output_dir: test_domain_18_model

# hyperparams
num_epochs: 300
num_diffusion_iters: 100
num_tests: 100
num_vis_demos: 3
num_train_demos: 500
num_warmup_steps: 500
pred_horizon: 16
obs_horizon: 2
action_horizon: 8
max_steps: 300
batch_size: 64
resize_scale: 96
wandb: true

