name: feature_analysis
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.7.2=h06a4308_0
  - expat=2.6.3=h6a678d5_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py312h06a4308_0
  - python=3.12.5=h5148396_1
  - readline=8.2=h5eee18b_0
  - setuptools=72.1.0=py312h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.44.0=py312h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - argparse==1.4.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - certifi==2024.8.30
      - cffi==1.17.1
      - charset-normalizer==3.3.2
      - click==8.1.7
      - cloudpickle==3.0.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - diffusers==0.30.2
      - docker-pycreds==0.4.0
      - executing==2.1.0
      - fasteners==0.19
      - filelock==3.13.1
      - fonttools==4.53.1
      - fsspec==2024.2.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gym==0.26.2
      - gym-notices==0.0.8
      - huggingface-hub==0.24.7
      - idna==3.8
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - ipython==8.27.0
      - jedi==0.19.1
      - jinja2==3.1.3
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==2.1.5
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - networkx==3.2.1
      - numcodecs==0.13.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.4.2.65
      - nvidia-cuda-cupti-cu12==12.4.99
      - nvidia-cuda-nvrtc-cu12==12.4.99
      - nvidia-cuda-runtime-cu12==12.4.99
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.0.44
      - nvidia-curand-cu12==10.3.5.119
      - nvidia-cusolver-cu12==11.6.0.99
      - nvidia-cusparse-cu12==12.3.0.142
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.4.99
      - opencv-python==4.10.0.84
      - packaging==24.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==10.2.0
      - platformdirs==4.3.3
      - plotly==5.24.1
      - prompt-toolkit==3.0.47
      - protobuf==5.28.1
      - psutil==6.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pygame==2.6.0
      - pygments==2.18.0
      - pymunk==6.8.1
      - pyparsing==3.1.4
      - python-dateutil==2.9.0.post0
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - safetensors==0.4.5
      - scikit-image==0.24.0
      - scikit-learn==1.5.2
      - scikit-video==1.1.11
      - scipy==1.14.1
      - sentry-sdk==2.14.0
      - setproctitle==1.3.3
      - shapely==2.0.6
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.12
      - tenacity==9.0.0
      - threadpoolctl==3.5.0
      - tifffile==2024.8.30
      - torch==2.4.1+cu124
      - torchaudio==2.4.1+cu124
      - torchvision==0.19.1+cu124
      - tqdm==4.66.5
      - traitlets==5.14.3
      - triton==3.0.0
      - typing==3.7.4.3
      - typing-extensions==4.9.0
      - urllib3==2.2.3
      - wandb==0.18.0
      - wcwidth==0.2.13
      - zarr==2.18.3
      - zipp==3.20.2

