_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.12.5
        t:
            "1":
                - 1
                - 41
                - 49
                - 55
                - 83
            "2":
                - 1
                - 41
                - 49
                - 55
                - 83
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.5
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
action_horizon:
    value: 8
batch_size:
    value: 64
dataset_path_dir:
    value: ../dataset_domain/domain18
display_name:
    value: test_domain_18_model
max_steps:
    value: 300
models_save_dir:
    value: test_domain_18_model
num_diffusion_iters:
    value: 100
num_epochs:
    value: 300
num_tests:
    value: 100
num_train_demos:
    value: 500
num_vis_demos:
    value: 3
num_warmup_steps:
    value: 500
obs_horizon:
    value: 2
output_dir:
    value: test_domain_18_model
pred_horizon:
    value: 16
resize_scale:
    value: 96
wandb:
    value: true
